version: 1.0.{build}

environment:
  nuget_publish:
    secure: rDlnJY8kT73e2PF3zSUxe4RO/pDFN1FW9YrDEItnjUOTVVUb3dfX/kN6Hnb5ExoF

branches:
  only:
    - master

skip_non_tags: true

before_build:
  - ps: nuget restore
    
build:
  project: InitialStateClient.sln
  verbosity: minimal
  publish_nuget: true

assembly_info:
  patch: true
  file: src/InitialStateClient/Properties/AssemblyInfo.cs
  assembly_version: $(appveyor_build_version).0
  assembly_file_version: $(appveyor_build_version).0
  assembly_informational_version: $(appveyor_build_version)

test:
  assemblies:
    - '**\*.Specs.dll'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true