version: 1.0.{build}

environment:
  nuget_publish:
    secure: rDlnJY8kT73e2PF3zSUxe4RO/pDFN1FW9YrDEItnjUOTVVUb3dfX/kN6Hnb5ExoF

branches:
  only:
    - master

before_build:
  - ps: nuget restore
    
build:
  project: InitialStateClient.sln
  verbosity: minimal
  publish_nuget: true

assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.cs'
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - '**\*.Specs.dll'

deploy:
  provider: NuGet
  #server:
  api_key:
    secure: rDlnJY8kT73e2PF3zSUxe4RO/pDFN1FW9YrDEItnjUOTVVUb3dfX/kN6Hnb5ExoF
  skip_symbols: true
